app/todos/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms import TextAreaField
from wtforms.validators import DataRequired


class TodoForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description')
    submit = SubmitField('Add Todo')

app/todos/__init__.py
from flask import Blueprint

todos_bp = Blueprint("todos", __name__, template_folder="templates", static_folder="static")
from . import views

app/todos/views.py
from flask import render_template, redirect, url_for, flash

from . import todos_bp
from .forms import TodoForm
from .. import db
from ..models import Todo

from config import navigation



# @app.route('/login', methods=['GET', 'POST'])
# def login():
#     os_info = platform.platform()
#     user_agent = request.headers.get('User-Agent')
#     current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
#
#     form = LoginForm()
#
#     if form.validate_on_submit():
#         username = form.username.data
#         password = form.password.data
#
#         if username in users_data and users_data[username]['password'] == password:
#
#             if form.remember.data:
#                 session['username'] = username
#                 flash('Ви успішно увійшли!', 'success')
#                 return redirect(url_for('info', username=username))
#             else:
#                 flash('Ви успішно увійшли але вас ніхто ніколи не згадає!', 'success')
#                 return redirect(url_for('page1', username=username))
#         else:
#             flash('Невірне ім\'я користувача або пароль', 'danger')
#
#     return render_template('login.html', os_info=os_info, user_agent=user_agent,
#                            current_time=current_time, form=form, navigation=navigation)


@todos_bp.route('/todos')
def todos():
    todos = Todo.query.all()
    return render_template('todos.html', todos=todos, navigation=navigation)


@todos_bp.route('/todo/<int:todo_id>')
def todo(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    return render_template('todo.html', todo=todo, navigation=navigation)


@todos_bp.route('/add_todo', methods=['GET', 'POST'])
def add_todo():
    form = TodoForm()

    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        new_todo = Todo(title=title, description=description)
        db.session.add(new_todo)
        db.session.commit()
        flash('Todo added successfully!', 'success')
        return redirect(url_for('todos.todos'))

    return render_template('add_todo.html', form=form, navigation=navigation)


@todos_bp.route('/delete_todo/<int:todo_id>')
def delete_todo(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    db.session.delete(todo)
    db.session.commit()
    flash('Todo deleted successfully!', 'success')
    return redirect(url_for('todos.todos'))

app/todos/templates/add_todo.html
<!-- app/templates/add_todo.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Add Todo</h2>
<form method="POST" action="{{ url_for('todos.add_todo') }}">
    {{ form.hidden_tag() }}
    <label for="title">Title:</label>
    {{ form.title(class="form-control") }}
    <label for="description">Description:</label>
    {{ form.description(class="form-control") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
<a href="{{ url_for('todos.todos') }}">Back to Todos</a>
{% endblock %}

app/todos/templates/todo.html
<!-- app/templates/todo.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>{{ todo.title }}</h2>
  <p>{{ todo.description }}</p>
  <p>Created on: {{ todo.date_created }}</p>
<a href="{{ url_for('todos.todos') }}">Back to Todos</a>
<a href="{{ url_for('todos.delete_todo', todo_id=todo.id) }}">Delete Todo</a>
{% endblock %}

app/todos/templates/todos.html
<!-- app/templates/todos.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Todos</h2>
  <ul>
    {% for todo in todos %}
      <li><a href="{{ url_for('todos.todo', todo_id=todo.id) }}">{{ todo.title }}</a> - {{ todo.date_created }}</li>
    {% endfor %}
  </ul>
<a href="{{ url_for('todos.add_todo') }}">Add Todo</a>
{% endblock %}