app/cookies/__init__.py
from flask import Blueprint

cookies_bp = Blueprint("cookies", __name__, template_folder="templates")
from . import views

app/cookies/views.py
import platform
from datetime import datetime

from flask import request, make_response, redirect, url_for, flash, render_template

from app.cookies import cookies_bp

from config import navigation


@cookies_bp.route('/info/<username>', methods=['GET', 'POST'])
def info(username):
    os_info = platform.platform()
    user_agent = request.headers.get('User-Agent')
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    current_cookies = request.cookies.items()

    if request.method == 'POST':
        if 'add_cookie_button' in request.form:
            key = request.form.get('cookie_key')
            value = request.form.get('cookie_value')
            expire_time = request.form.get('expire_time')

            if key and value and expire_time:
                response = make_response(redirect(url_for('info', username=username)))
                response.set_cookie(key, value, max_age=int(expire_time))
                flash('Cookie додано успішно!', 'success')
                return response

        elif 'remove_cookie_button' in request.form:
            key_to_remove = request.form.get('key_to_remove')

            if key_to_remove:
                response = make_response(redirect(url_for('info', username=username)))
                response.delete_cookie(key_to_remove)
                flash('Cookie видалено успішно!', 'success')
                return response

        elif 'remove_all_cookies_button' in request.form:
            response = make_response(redirect(url_for('info', username=username)))

            for key, _ in current_cookies:
                response.delete_cookie(key)
                flash('Усі Cookie видалено успішно!', 'success')
            return response

    return render_template('info.html', username=username, os_info=os_info, user_agent=user_agent,
                           current_time=current_time, current_cookies=current_cookies, navigation=navigation)

app/cookies/templates/info.html
{% extends 'base.html' %}

{% block title %}Інфо{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card border-primary">
        <div class="card-header bg-primary text-white">
            <h2 class="mb-0 display-4">Ласкаво просимо до сторінки Інфо, {{ username }}!</h2>
        </div>
        <div class="card-body">
            <p class="lead">Тут ви можете отримати інформацію та вийти з системи.</p>

            <form method="post" action="{{ url_for('accounting.login') }}">
                <button type="submit" class="btn btn-danger">Вийти</button>
            </form>

            <form method="post" action="{{ url_for('cookies.info', username=username) }}" class="mt-4">
                <h3>Додати кукі:</h3>
                <div class="row">
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label for="cookie_key" class="form-label">Ключ кукі:</label>
                            <input type="text" class="form-control" id="cookie_key" name="cookie_key" required>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label for="cookie_value" class="form-label">Значення кукі:</label>
                            <input type="text" class="form-control" id="cookie_value" name="cookie_value" required>
                        </div>
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label for="expire_time" class="form-label">Термін дії (сек):</label>
                            <input type="number" class="form-control" id="expire_time" name="expire_time" required>
                        </div>
                    </div>
                </div>
                <button type="submit" name="add_cookie_button" class="btn btn-success">Додати кукі</button>
            </form>

            <form method="post" action="{{ url_for('cookies.info', username=username) }}" class="mt-4">
                <h3>Видалити кукі за ключем:</h3>
                <div class="mb-3">
                    <label for="key_to_remove" class="form-label">Ключ кукі для видалення:</label>
                    <input type="text" class="form-control" id="key_to_remove" name="key_to_remove" required>
                </div>
                <button type="submit" name="remove_cookie_button" class="btn btn-warning">Видалити кукі за ключем
                </button>
            </form>

            <form method="post" action="{{ url_for('cookies.info', username=username) }}" class="mt-4">
                <h3>Видалити всі кукі:</h3>
                <button type="submit" name="remove_all_cookies_button" class="btn btn-danger">Видалити всі кукі</button>
            </form>

            <div class="mt-4 table-responsive">
                <h3>Список всіх кукі:</h3>
                {% if current_cookies %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Ключ</th>
                        <th scope="col">Значення</th>
                        <th scope="col">Термін дії</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for key, value in current_cookies %}
                    <tr>
                        <td>{{ key }}</td>
                        <td>{{ value }}</td>
                        <td>{{ expire_time }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>Немає збережених кукі.</p>
                {% endif %}
            </div>

        </div>
        <div class="card-footer text-muted mt-4">
            © Прикарпатський національний університет імені Василя Стефаника
            Тел. (0342) 75-23-51, E-mail: office@pnu.edu.ua
        </div>
    </div>
</div>
{% endblock %}