app/portfolio/__init__.py
from flask import Blueprint

portfolio_bp = Blueprint("portfolio", __name__, template_folder="templates", static_folder="static")
from . import views

app/portfolio/views.py
import platform
from datetime import datetime

from flask import render_template, flash, redirect, url_for, request

from . import portfolio_bp

from config import navigation


@portfolio_bp.route('/')
def home():
    os_info = platform.platform()
    user_agent = request.headers.get('User-Agent')
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    username = None

    return render_template('page1.html', os_info=os_info, user_agent=user_agent, current_time=current_time,
                           username=username, is_home=True, navigation=navigation)


@portfolio_bp.route('/page1')
def page1():
    os_info = platform.platform()
    user_agent = request.headers.get('User-Agent')
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    username = None
    return render_template('page1.html', os_info=os_info, user_agent=user_agent, current_time=current_time,
                           username=username, is_home=True, navigation=navigation)


@portfolio_bp.route('/page2')
def page2():
    os_info = platform.platform()
    user_agent = request.headers.get('User-Agent')
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    return render_template('page2.html', os_info=os_info, user_agent=user_agent, current_time=current_time,
                           navigation=navigation)


@portfolio_bp.route('/page3')
def page3():
    os_info = platform.platform()
    user_agent = request.headers.get('User-Agent')
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    return render_template('page3.html', os_info=os_info, user_agent=user_agent, current_time=current_time,
                           navigation=navigation)


@portfolio_bp.route('/skills', methods=['GET', 'POST'])
def display_skills():
    os_info = platform.platform()
    user_agent = request.headers.get('User-Agent')
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    if request.method == 'POST':
        skill_name = request.form.get('skill_name')
        for i, skill in enumerate(my_skills):
            if skill_name.lower() in skill.lower():
                flash(f"Навичка '{skill}' знайдена!", 'success')
                return redirect(url_for('portfolio.display_skill', id=i))

        flash("Навичка не знайдена.", 'danger')

    return render_template('skills.html', my_skills=my_skills, os_info=os_info, user_agent=user_agent,
                           current_time=current_time, navigation=navigation)


@portfolio_bp.route('/skills/<int:id>')
def display_skill(id):
    os_info = platform.platform()
    user_agent = request.headers.get('User-Agent')
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    if 0 <= id < len(my_skills):
        return f"Навичка з id {id}: {my_skills[id]}"
    else:
        return "Навичка не знайдена."

app/portfolio/templates/page1.html
{% extends 'base.html' %}

{% block title %}Сторінка 1{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>Про мене</h1>

    <p>Привіт  {% if username %} {{ username }} {% endif %}! Мене звуть [Ваше ім'я]. Я [додайте опис про себе].</p>
    <p>Я маю досвід у розробці веб-додатків з використанням Python та Flask.</p>
    <img id="about-image" src="{{ url_for('static', filename='images/me.jpg') }}" alt="Моя фотографія">
</div>
{% endblock %}

app/portfolio/templates/page2.html
{% extends 'base.html' %}

{% block title %}Сторінка 2{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>Проекти</h1>
    <p>Ось деякі з моїх проектів:</p>
    <ul>
        <li>Проєкт 1: [назва проєкту 1] <img class="project-image" src="{{ url_for('static', filename='images/p1.png') }}" alt="p1"> </li>
        <li>Проєкт 2: [назва проєкту 2] <img class="project-image" src="{{ url_for('static', filename='images/p2.png') }}" alt="p2"> </li>
        <li>Проєкт 3: [назва проєкту 3] <img class="project-image" src="{{ url_for('static', filename='images/p3.png') }}" alt="p1"> </li>

    </ul>
</div>
{% endblock %}

app/portfolio/templates/page3.html
{% extends 'base.html' %}

{% block title %}Сторінка 3{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>Контакти</h1>
    <p>Я завжди готовий спілкуватися. Зв'яжіться зі мною за допомогою:</p>
    <ul>
        <li>Email: [ваш email]</li>
        <li>Телефон: [ваш номер телефону]</li>
        <li>Соціальні мережі: [посилання на ваші профілі]</li>
    </ul>
<img id="contact-image" src="{{ url_for('static', filename='images/me2.jpg') }}" alt="Зображення 3">
</div>
{% endblock %}

app/portfolio/templates/skills.html
{% extends 'base.html' %}

{% block title %}Skills{% endblock %}

{% block content %}
    <h1>Навички</h1>
    <p>Тут ви можете знайти мої навички та уміння.</p>
    <ul>
        {% if my_skills %}
            {% for my_skill in my_skills %}
                <li>{{ my_skill }}</li>
            {% endfor %}
        {% else %}
            {% if skill %}
                <li>{{ skill }}</li>
            {% else %}
                <h2> НАВИЧКУ НЕ ЗНАЙДЕно </h2>
            {% endif %}
        {% endif %}
    </ul>

    <h2>Пошук навичок</h2>
<form action="{{ url_for('portfolio.display_skills') }}" method="post">
        <div class="form-group">
            <input type="text" name="skill_name" placeholder="Назва навички" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Пошук</button>
    </form>
    </div>
{% endblock %}